DATA:
  END_DATE: '2024-11-30'
  MODE: rule
  PATH: output/job-catalog-simulator-simulation-characteristics-20251221-184357-5d908492/products.csv
  SEED: 42
  START_DATE: '2024-11-01'
  TYPE: simulator
MEASUREMENT:
  MODEL: interrupted_time_series
  PARAMS:
    DEPENDENT_VARIABLE: revenue
    END_DATE: '2024-11-30'
    INTERVENTION_DATE: '2024-11-15'
    START_DATE: '2024-11-01'
OUTPUT:
  PATH: output
