STORAGE:
  PATH: output/demo_model_selection
RULE:
  PRODUCTS:
    FUNCTION: simulate_products_rule_based
    PARAMS:
      num_products: 20000
      seed: 42
  METRICS:
    FUNCTION: simulate_metrics_rule_based
    PARAMS:
      date_start: "2024-01-08"
      date_end: "2024-01-08"
      seed: 42
      sale_prob: 1.0
