name: tools-impact-engine
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pandas
  - pyyaml
  - statsmodels
  - pytest
  - pytest-cov
  - black
  - ruff
  - pre-commit
  - pip
  - pip:
      - "online_retail_simulator @ git+https://github.com/eisenhauerIO/tools-catalog-generator.git@peisen_score"
      - "artifact-store @ git+https://github.com/eisenhauerIO/utils-artifact-store.git@b389fc5c3e558659626408996d9c896daed00b68"
      - -e .
