[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "impact_engine"
version = "0.1.0"
description = "A package for evaluating product impact."
authors = [
  { name = "eisenhauerIO", email = "info@eisenhauer.io" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "pandas",
  "pyyaml",
  "statsmodels",
  "online_retail_simulator @ file:///home/peisenha/office/business/eisenhauer-io/tools/impact-engine/_external/tools-catalog-generator",
  "artifact-store @ file:///home/peisenha/office/business/eisenhauer-io/tools/impact-engine/_external/utils-artifact-store"
]

[project.urls]
Homepage = "https://github.com/eisenhauerIO/tools-impact-engine"

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov",
  "black",
  "ruff"
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["science/impact_engine"]

[tool.hatch.envs.default]
dependencies = [
  "pytest",
  "black"
]

[tool.hatch.envs.default.scripts]
test = "pytest science/impact_engine/tests/ -v"
format = "black ."

[tool.hatch.envs.docs]
dependencies = [
  "sphinx>=7.0.0",
  "sphinx-rtd-theme>=1.3.0",
  "myst-parser>=2.0.0",
  "linkify-it-py>=2.0.0",
  "sphinx-autodoc-typehints>=1.12.0"
]
