[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "impact_engine"
version = "0.1.0"
description = "A package for evaluating product impact."
authors = [
  { name = "eisenhauerIO", email = "info@eisenhauer.io" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "pandas",
  "pyyaml",
  "statsmodels",
  "online_retail_simulator[light] @ git+https://github.com/eisenhauerIO/tools-catalog-generator.git"
]

[project.urls]
Homepage = "https://github.com/eisenhauerIO/tools-impact-engine"

[tool.hatch.metadata]
allow-direct-references = true


